daemonset:
  enabled: true

# Minimal resources for agent
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

configReloader:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

# Logs -> Loki
loki:
  enabled: true
  url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push

# Traces -> Tempo (OTLP/Zipkin/Jaeger endpoints depend on what your agent uses)
tempo:
  enabled: true
  url: http://tempo.observability.svc.cluster.local:9411/api/v2/spans

# Metrics -> Mimir / prometheus remote write (configure as appropriate)
metrics:
  enabled: true
  remote_write:
    - url: http://mimir.observability.svc.cluster.local:8080/api/v1/push

alloy:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
