apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-token
  namespace: argocd
spec:
  encryptedData:
    argocd.token: <base64-encoded-encrypted-token> # Replace with output from kubeseal
  template:
    metadata:
      name: argocd-image-updater-secret
    type: Opaque
