apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd
data:
  git.commit-message-template: |
    Auto-commit by Argocd Image Updater [{{ .AppName }}]

    {{ range .AppChanges -}}
    updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}
  log.level: debug
  registries.conf: |
    registries:
    - name: us-central1-docker.pkg.dev
      api_url: https://us-central1-docker.pkg.dev
      ping: no
      credentials: pullsecret:argocd/gcp-artifact-registry
      prefix: us-central1-docker.pkg.dev
