apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: guild-placeholder
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: discord-bot
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: guild-placeholder
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
