apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-secret-reader
  namespace: frolf-bot
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["backend-secrets"]
    verbs: ["get"]
