serviceAccount:
  create: false
  name: postgres-secret-accessor

# Postgres for Frolf Bot (isolated)
auth:
  existingSecret: backend-secrets
  existingSecretNamespace: frolf-bot
  secretKeys:
    userPasswordKey: DB_PASSWORD
    adminPasswordKey: DB_PASSWORD
    replicationPasswordKey: DB_PASSWORD
  username: frolf
  database: frolfbot

primary:
  initContainers:
    - name: wait-for-secret
      image: busybox:1.35
      command: ["sh", "-c"]
      args:
        - |
          echo "Waiting for backend-secrets to be created..."
          until kubectl get secret backend-secrets -n frolf-bot >/dev/null 2>&1; do
            echo "Secret not found yet. Waiting 5 seconds..."
            sleep 5
          done
          echo "Secret found!"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
