# Postgres for Frolf Bot
auth:
  existingSecret: backend-secrets
  secretKeys:
    userPasswordKey: DB_PASSWORD
    adminPasswordKey: DB_PASSWORD
    replicationPasswordKey: DB_PASSWORD
  username: local
  database: frolfbot

primary:
  persistence:
    enabled: true
    storageClass: ""
    existingClaim: frolf-db-pvc
    size: 10Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
