rbac:
  enabled: true
config:
  argocd:
    serverAddress: "argocd-server.argocd.svc.cluster.local"
    tokenSecretName: "argocd-image-updater-secret"
  gitCommitUser: "argocd-image-updater"
  gitCommitMail: "argocd-image-updater@noreply.com"
  logLevel: "debug"
  registries:
    - name: Google Artifact Registry
      api_url: https://us-central1-docker.pkg.dev/v2
      prefix: us-central1-docker.pkg.dev
      ping: yes
      credentials: pullsecret:argocd/gcp-artifact-registry
serviceAccount:
  create: true

extraEnvVars:
  - name: ARGOCD_SERVER
    value: "argocd-server.argocd.svc.cluster.local"
  - name: ARGOCD_TOKEN
    valueFrom:
      secretKeyRef:
        name: argocd-image-updater-secret
        key: argocd.token
