rbac:
  enabled: true
config:
  argocd:
    serverAddress: "argocd-server.argocd.svc.cluster.local"
    tokenSecretName: "argocd-image-updater-secret"
  gitCommitUser: "argocd-image-updater"
  gitCommitMail: "argocd-image-updater@noreply.com"
  registries:
    - name: Google Artifact Registry
      api_url: https://us-central1-docker.pkg.dev
      prefix: us-central1-docker.pkg.dev
      ping: no
      credentials: ext:/bin/sh -c 'echo "_json_key:$(base64 -w 0 /etc/gcp/key.json)"'
serviceAccount:
  create: true

extraEnvVars:
  - name: ARGOCD_SERVER
    value: "argocd-server.argocd.svc.cluster.local"
  - name: ARGOCD_TOKEN
    valueFrom:
      secretKeyRef:
        name: argocd-image-updater-secret
        key: argocd.token
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/gcp/key.json

extraVolumes:
  - name: gcp-key
    secret:
      secretName: gcp-sa-key

extraVolumeMounts:
  - name: gcp-key
    mountPath: /etc/gcp
    readOnly: true
