---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocir-secret
  namespace: frolf-bot
spec:
  encryptedData:
    .dockerconfigjson: AgAEiazvIQ/Ax0KlajgQeWe7wRYIfUuj/VqsHiWD1f8arnUyBu8sya+NJ6Ws0MnERzhdnXNUbgL8kIexFEOZV4F2KHp79OFFpluqUG75W7XoRPRwm38B16SuLB51mkPu1ioB9sVvFDrb6eJTlpVRsxERBzD7KRYSGbRidASx03+rks/HGnoXwMlmNdmYmpCfb1Chck93Swztif97xMFcNr5y/KwO01mmCun3uQ8r+++gHqCZZcAo6Thbndg3AVQREVVGEcPx/29hq+poBrJLxng2cuxrIj19eyymYTJJWQx1y2wf+QmtDoSFthezZdT/VjjCjfSsQg/ZYlZha/hi0lsxHrreKNl7CcnQ8vZBS9owjvklCqL+b/JMiqIeJDRCCxVcUJ5IkkJqyLl0SlxfBXKj97h0ogn1SCCaJCcHbo+3fEjBPqrj34KII4vYlkYdCuf1855p/IBrMCcEfK3MHUzC07SI5qBgYM7jOfCI+JSX8PJZwPAaVphUhnx1k88ta/hxTp+qCNHwr8ZPF147JJT8N4EpxCLwV+VxWs3rabl0xG/3ielDeCYpSPy5go3v8EZoDsGWon55lqC0NRrvfOHY1LjNQgBAxHfRvM5LbBrcccVf8Cl6j2OwlGfJMlEPoHpFl4/TBro9lyIX3e8NxDQQVy2IDQ/OHhL3/ii/GJ3ESpMbO/4zlRkeMo8pHM7Ps7MtfOHJzR/EL8qcskhcVbnVw88aci4UJinsDab69Yee6d81Mxu+mOoetpUlLN6Ql1uYfZlHstZWq4PLM7gCEgcamaMEC2cNF+tagHtAt16hkkE0TJxSBKeLAG27Aq1F5p/qF2YYzYjIS82BF5hKFBjW1wUb9CpEn58k7v8BwCgtduFyRwuIy0rftRxaNTEeI0dr6KLoqR42qW0brt2K6jDaaoWDKOv7qxkOYiKNhWO+8syy1KE/1kDC/lYYWiRNLlGXEo4OjbIRt7Pyxp66JK0hLtIYtKBYAzO+lu0jk7Lde2hlOqo8ivU/OrH07vrae6xoWdKZ
  template:
    metadata:
      name: ocir-secret
      namespace: frolf-bot
    type: kubernetes.io/dockerconfigjson
