apiVersion: v1
kind: PersistentVolume
metadata:
  name: mimir-frolf-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mimir-local
  local:
    path: /mnt/frolf_grafana/mimir
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - resume-project-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mimir-frolf-pvc
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mimir-local
  resources:
    requests:
      storage: 10Gi
