apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-frolf-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/frolf_grafana/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - resume-project-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-frolf-pvc
  namespace: frolf-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
