apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
---
# Local Node-only storage class removed (mimir-local removed to prevent hostPath PVs)
# If you need to re-enable local volumes for development, re-add a local, dev-only
# StorageClass in a separate repo or a dev-only cluster-resources overlay.
