kustomize:
  images:
  - us-central1-docker.pkg.dev/resume-portfolio-project/frolf-bot/discord-frolf-bot-acdcbeeada7153bab04a7fb26870d1c5:latest
  - us-central1-docker.pkg.dev/resume-portfolio-project/frolf-bot/discord-frolf-bot:latest@sha256:114d17217e2fd4d4cedf5aa498d7ee72d9c58e02a6b4cca2409433e0b42d09a9
