apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - discord-deployment.yaml

images:
  - name: us-central1-docker.pkg.dev/resume-portfolio-project/frolf-bot/discord-frolf-bot
    newTag: 9f31817
