adminUser: admin
# DO NOT put real secrets in Git: use a Kubernetes Secret + sealed-secrets / sops.
# For quick testing you can set this, but replace for production.
adminPassword: changeme

persistence:
  enabled: true
  existingClaim: grafana-frolf-pvc
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: mimir
        access: proxy
        url: http://mimir-query-frontend.observability.svc.cluster.local:8080
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3200
