adminUser: admin
# DO NOT put real secrets in Git: use a Kubernetes Secret + sealed-secrets / sops.
# For quick testing you can set this, but replace for production.
adminPassword: changeme

service:
  type: LoadBalancer # or NodePort; on GCE you can use LoadBalancer

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi

initContainers:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir.observability.svc.cluster.local:8080 # adjust port to your Mimir service
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
