logLevel: "DEBUG"

rbac:
  create: true

serviceAccount:
  create: true

controller:
  hostNetwork: true
  extraEnvVars:
    - name: KUBERNETES_SERVICE_HOST
      value: "127.0.0.1"
    - name: KUBERNETES_SERVICE_PORT
      value: "6443"

updateStatus: false

livenessProbe:
  initialDelaySeconds: 60

readinessProbe:
  initialDelaySeconds: 60

startupProbe:
  enabled: true
  initialDelaySeconds: 60
