apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  username: github-actions[bot] # For Git commits
  password: YOUR_GITHUB_TOKEN # GitHub token with repo write access
  token: YOUR_ARGOCD_TOKEN # ArgoCD API token (optional, for external access)
  registry_key: YOUR_GCP_SA_KEY_JSON # GCP service account key JSON for registry auth
