# Frolf Bot Discord App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frolf-bot-discord
  namespace: frolf-bot
  labels:
    app: frolf-bot-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frolf-bot-discord
  template:
    metadata:
      labels:
        app: frolf-bot-discord
    spec:
      containers:
        - name: discord
          image: us-central1-docker.pkg.dev/resume-portfolio-project/frolf-bot/frolf-bot-discord:test
          ports:
            - containerPort: 8081
            - containerPort: 6060
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-secrets
                  key: token
            - name: DISCORD_APP_ID
              valueFrom:
                secretKeyRef:
                  name: discord-secrets
                  key: app-id
            - name: BACKEND_URL
              value: "http://frolf-bot-backend.frolf-bot.svc.cluster.local"
            - name: NATS_URL
              value: "nats://nats.nats-frolf.svc.cluster.local:4222"
            - name: LOG_LEVEL
              value: "debug"
            - name: ENV
              value: "development"
            - name: ENVIRONMENT
              value: "development"
            - name: CONFIG_FILE
              value: "" # Use environment variables instead of config file
            # Completely disable all telemetry for local development
            # Enable Loki logging for development debugging
            - name: LOKI_URL
              value: "http://loki.monitoring.svc.cluster.local:3100"
            - name: METRICS_ADDRESS
              value: "alloy-otlp.monitoring.svc.cluster.local:4317"
            - name: METRICS_ENABLED
              value: "true"
            # Disable OpenTelemetry completely
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_SDK_DISABLED
              value: "false"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy-otlp.monitoring.svc.cluster.local:4317"
            - name: TEMPO_ENDPOINT
              value: "alloy-otlp.monitoring.svc.cluster.local:4317"
            - name: TEMPO_INSECURE
              value: "true"
            - name: TEMPO_SAMPLE_RATE
              value: "0"
            - name: PPROF_ENABLED
              value: "true"
            - name: PPROF_ADDR
              value: ":6060"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
